// DO NOT EDIT.
// This file was generated automatically
// from gen.go. Please do not edit this file.

// package md1 implements basic 1D math useful for 3D graphics applications.
// Functions in this package have their OpenGL equivalent which is usually of the same name.
package md1

import math "math"

// Sign returns -1, 0, or 1 for negative, zero or positive x argument, respectively, just like OpenGL's "sign" function.
func Sign(x float64) float64 {
	if x == 0 {
		return 0
	}
	return math.Copysign(1, x)
}

// Clamp returns value v clamped between Min and Max.
func Clamp(v, Min, Max float64) float64 {
	return math.Min(Max, math.Max(v, Min))
}

// Interp performs the linear interpolation between x and y, mapping with a in interval [0,1].
// This function is known as "mix" in OpenGL.
func Interp(x, y, a float64) float64 {
	return x*(1-a) + y*a
}

// SmoothStep performs smooth cubic hermite interpolation between 0 and 1 when edge0 < x < edge1.
func SmoothStep(edge0, edge1, x float64) float64 {
	t := Clamp((x-edge0)/(edge1-edge0), 0, 1)
	return t * t * (3 - 2*t)
}

// EqualWithinAbs checks if a and b are within tol of eachother.
func EqualWithinAbs(a, b, tol float64) bool {
	return math.Abs(a-b) <= tol
}
